<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1" />
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1" />
    <PackageReference Include="Moq" Version="4.20.70" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../NovelCsam.Helpers/NovelCsam.Helpers.csproj" />
    <ProjectReference Include="../NovelCsam.Models/NovelCsam.Models.csproj" />
    <ProjectReference Include="../NovelCsam.Functions/NovelCsam.Functions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <Using Include="Moq" />
    <Using Include="Moq.Language.Flow" />
    <Using Include="NovelCsam.Helpers" />
    <Using Include="NovelCsam.Helpers.Interfaces" />
    <Using Include="NovelCsam.Models" />
    <Using Include="NovelCsam.Functions.Configuration" />
  </ItemGroup>

</Project>
